const products = [
    { id: 1, name: "Pijama de Seda Clássico", price: 259.90, installments: 10, category: "feminino", style: "manga longa", fabric: "seda", color: "preto", sizes: ["P", "M", "G"], images: ["images/pijama-seda-preto-1.jpg", "images/pijama-seda-preto-2.jpg"], description: "Pijama de seda pura com toque suave e caimento perfeito. Ideal para noites de luxo e conforto. Composição: 100% Seda.", rating: 4.8, reviews: 23 },
    { id: 2, name: "Pijama de Algodão Estampado", price: 129.90, installments: 6, category: "feminino", style: "manga curta", fabric: "algodao", color: "azul", sizes: ["P", "M", "G", "GG"], images: ["images/pijama-algodao-azul-1.jpg", "images/pijama-algodao-azul-2.jpg"], description: "Confortável e divertido, este pijama de algodão estampado é perfeito para o dia a dia. Composição: 100% Algodão.", rating: 4.5, reviews: 45 },
    { id: 3, name: "Pijama Masculino Flanelado", price: 189.90, installments: 8, category: "masculino", style: "manga longa", fabric: "flanela", color: "vermelho", sizes: ["M", "G", "GG"], images: ["images/pijama-flanela-vermelho-1.jpg", "images/pijama-flanela-vermelho-2.jpg"], description: "Mantenha-se aquecido com nosso pijama de flanela xadrez. Perfeito para noites frias. Composição: 80% Algodão, 20% Poliéster.", rating: 4.7, reviews: 18 },
    { id: 4, name: "Pijama Infantil Dinossauros", price: 99.90, installments: 5, category: "infantil", style: "manga longa", fabric: "algodao", color: "verde", sizes: ["2", "4", "6", "8"], images: ["images/pijama-infantil-dino-1.jpg", "images/pijama-infantil-dino-2.jpg"], description: "As crianças vão amar este pijama que brilha no escuro com estampa de dinossauros. Composição: 100% Algodão.", rating: 4.9, reviews: 52 },
    { id: 5, name: "Robe de Cetim Floral", price: 179.90, installments: 7, category: "feminino", style: "robe", fabric: "cetim", color: "rosa", sizes: ["P", "M", "G"], images: ["images/robe-cetim-floral-1.jpg", "images/robe-cetim-floral-2.jpg"], description: "Robe de cetim elegante com estampa floral delicada. Perfeito para momentos de relaxamento com um toque de sofisticação. Composição: 100% Poliéster Acetinado.", rating: 4.6, reviews: 15 },
    { id: 6, name: "Pijama de Malha Listrado Masculino", price: 149.50, installments: 6, category: "masculino", style: "manga curta", fabric: "malha", color: "cinza", sizes: ["P", "M", "G", "GG"], images: ["images/pijama-malha-cinza-1.jpg", "images/pijama-malha-cinza-2.jpg"], description: "Pijama masculino super confortável em malha de algodão com listras discretas. Ideal para o dia a dia e uma ótima noite de sono. Composição: 100% Algodão.", rating: 4.4, reviews: 28 },
    { id: 7, name: "Camisola Infantil Princesa", price: 89.90, installments: 4, category: "infantil", style: "camisola", fabric: "algodao", color: "branco", sizes: ["4", "6", "8", "10"], images: ["images/camisola-princesa-branca-1.jpg", "images/camisola-princesa-branca-2.jpg"], description: "Camisola encantadora para as pequenas princesas, feita em algodão macio com detalhes em renda e estampa delicada. Composição: 100% Algodão.", rating: 4.8, reviews: 35 },
    { id: 8, name: "Pijama Americano Poá Feminino", price: 199.00, installments: 8, category: "feminino", style: "manga longa", fabric: "viscose", color: "marinho", sizes: ["PP", "P", "M", "G"], images: ["images/pijama-poa-marinho-1.jpg", "images/pijama-poa-marinho-2.jpg"], description: "Clássico e charmoso, o pijama americano em viscose com estampa poá oferece conforto e estilo. Fechamento com botões e vivos contrastantes. Composição: 100% Viscose.", rating: 4.7, reviews: 22 }
];
